export const MODAL_TYPE_ITEM = "MODAL_TYPE_ITEM";
export const MODAL_TYPE_STANDARD_ITEM = "MODAL_TYPE_STANDARD_ITEM";

export type ModalType = typeof MODAL_TYPE_ITEM | typeof MODAL_TYPE_STANDARD_ITEM;
