# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: yarn install
    - name: Build project
      run: yarn build
    - name: Test project
      run: yarn test --passWithNoTests
    
  deploy:
    runs-on: self-hosted
    
    needs: build
    
    steps:
    - uses: sebastianpopp/ftp-action@v2.0.0
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        forceSsl: true
        localDir: "build"
